version: '3.8'
services:
  react:
    build: ./frontend/here-law
    ports:
      - "3000:80"
    networks:
      - app-network

  spring:
    build: ./backend/spring
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
  
  fastapi:
    build: ./backend/fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - spring
      - fastapi
    networks:
      - app-network
    
networks:
  app-network:

volumes:
  postgres-data: