version: '3.8'
services:
  react:
    image: happyyongku/j11b109:react
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./dist:/app/dist

  spring:
    image: happyyongku/j11b109:spring
    expose:
      - "8080"
    networks:
      - app-network
    # depends_on:
    #   - postgres
  
  fastapi:
    image: happyyongku/j11b109:fastapi
    expose:
      - "8000"
    networks:
      - app-network
    # depends_on:
    #   - postgres

  nginx:
    image: happyyongku/j11b109:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      # - ./dist:/usr/share/nginx/html
    depends_on:
      - react
    #   - spring
      - fastapi
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      retries: 3
    
networks:
  app-network:
