version: '3.8'
services:
  react:
    image: happyyongku/j11b109:react
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./dist:/app/dist

  spring:
    image: happyyongku/j11b109:spring
    expose:
      - "8080"
    networks:
      - app-network
    environment:
      DB_DOMAIN: ${DB_DOMAIN}
      DB_PORT: ${DB_PORT_SPRING}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      - postgres
  
  fastapi:
    image: happyyongku/j11b109:fastapi
    expose:
      - "8000"
    networks:
      - app-network
    environment:
      DB_DOMAIN: ${DB_DOMAIN}
      DB_PORT: ${DB_PORT_FASTAPI}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  nginx:
    image: happyyongku/j11b109:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - certs:/etc/letsencrypt/live/j11b109.p.ssafy.io
      - ./certs/live/j11b109.p.ssafy.io:/etc/letsencrypt/live/j11b109.p.ssafy.io

    command: nginx -g 'daemon off;'

    depends_on:
      - react
    #   - spring
      - fastapi
    networks:
      - app-network
  
  postgres:
    image: happyyongku/j11b109:postgres
    ports:
      - "5433:5432"
      - "3345:5432"
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  certs:
    driver: local
  database:
    driver: local
networks:
  app-network:
