version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - spring
      - fastapi
    networks:
      - app-network

  react:
    build: ./frontend/here_law
    expose:
      - "3000"
    networks:
      - app-network

  spring:
    build: ./backend/spring
    expose:
      - "8080"
    networks:
      - app-network
    # depends_on:
    #   - postgres
  
  fastapi:
    build: ./backend/fastapi_ec2
    expose:
      - "8000"
    networks:
      - app-network
    # depends_on:
    #   - postgres
    
networks:
  app-network:
